// Ensure this file is placed adjacent to the pb_data folder of your PocketBase database
onRecordCreate(async (e) => {
    try {
        const userId = e.record.get("user");
        const userRecord = await $app.findRecordById("users", userId);
        const email = userRecord.get("email");
        const userName = userRecord.get("name");
        const creditType = e.record.get("type");
        const credits = e.record.get("credits");
        let subject = '';
        let htmlContent = '';

        if (creditType === "event") {
            const eventName = e.record.get("event");
            subject = `CREDITED FOR: ${eventName}`;
            htmlContent = `
        <p>Dear ${userName},</p>
        <p>You have received ${credits} event credits for participating in ${eventName}.</p>
        <p>Sincerely,</p>
        <p>ARISTA Web Committee</p>
        <p>This is an automated email generated by the website -- if you have received this email in error, please contact us at stuyaristanycweb@gmail.com</p>
    `;
            console.log(`event credits`);
        } else if (creditType === "tutoring") {
            const sessionId = e.record.get("session");
            const sessionDetails = await $app.findRecordById("tutoringSessions", sessionId);
            const tuteeId = sessionDetails.get("tutee");
            const tutee = await $app.findRecordById("users", tuteeId);
            const tutoringRequestId = sessionDetails.get("tutoringRequest");
            const tutoringRequest = await $app.findRecordById("tutoringRequests", tutoringRequestId);
            const subjectName = tutoringRequest.get("class");
            subject = `CREDITED FOR: ${sessionDetails.get("name")}`;
            htmlContent = htmlContent = `
        <p>Dear ${userName},</p>
        <p>You have received ${credits} tutor credits for tutoring ${tutee.get("name")} in ${subjectName}.</p>
        <p>Sincerely,</p>
        <p>ARISTA Web Committee</p>
        <p>This is an automated email generated by the website -- if you have received this email in error, please contact us at stuyaristanycweb@gmail.com</p>
    `;
            console.log(`tutor credits`);
        } else {
            const explanation = e.record.get("manualExplanation");
            subject = `OTHER CREDITS RECEIVED`;
            htmlContent = `
        <p>Dear ${userName},</p>
        <p>You have received ${credits} other credits for ${explanation}.</p>
        <p>Sincerely,</p>
        <p>ARISTA Web Committee</p>
        <p>This is an automated email generated by the website -- if you have received this email in error, please contact us at stuyaristanycweb@gmail.com</p>
    `;
            console.log(`other credits`);
        }

        const message = new MailerMessage({
            from: {
                address: $app.settings().meta.senderAddress,
                name: $app.settings().meta.senderName,
            },
            to: [{ address: email }],
            subject: subject,
            html: htmlContent,
        });

        await $app.newMailClient().send(message);
        console.log(`Credit notification email sent to ${email}`);
    } catch (error) {
        console.error('Error processing record creation:', error);
    } finally {
        e.next();
    }
}, "credits");


