// note, this file and folder must be moved next to the pb_data folder of the pocketbase database folder
onRecordAfterUpdateRequest((e) => {
    const old_record = e.record.originalCopy();
    const old_signups = old_record.get("signed_up");
    const current_signups = e.record.get("signed_up");

    const new_signups = current_signups.filter(v => !old_signups.includes(v));

    console.log(`New signups: ${new_signups}`);

    for (const signup_user_id of new_signups) {
        const user = $app.dao().findRecordById("users", signup_user_id);
        const email = user.get("email");

        const message = new MailerMessage({
            from: {
                address: $app.settings().meta.senderAddress,
                name: $app.settings().meta.senderName,
            },
            to: [{ address: email }],
            subject: `Signed up for ${e.record.get("name")}`,
            html: `
<p>Dear ${user.get("name")},</p>

<p>You have signed up for ${e.record.get("name")}.</p>

<p>Sincerely,</p>
<p>ARISTA Web Committee</p>

<p>This is an automated email generated by the website -- if you have received this email in error, please contact us at stuyaristanycweb@gmail.com</p>
`, // A template should probably be used here but this is good enough for now.
        })

        $app.newMailClient().send(message);
        console.log(`Signup email sent to ${email}`);

    }
})